language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install git+git://github.com/WMD-group/MacroDensity.git
# command to run tests
script:
  - py.test tests/unit_tests.py # or py.test for Python versions 3.5 and below
